---
---

<link rel="stylesheet" href="styles.css" type="text/css">
Publications:

Kennedy-Turner, K., Serbin, L.A., Stack, D.M., Dickson, D.J., Ledingham, J.E., Schwartzman, A.E. (2019) [Prevention of Criminal Offending: The Intervening and Protective Effects of Education for Aggressive Youth](https://doi.org/10.1093/bjc/azz053)

As a PhD Candidate, I am involved in several projects under the supervision of Drs. [Lisa Serbin](https://www.concordia.ca/artsci/psychology/faculty.html?fpid=lisa-serbin) and [Dale Stack](https://www.concordia.ca/artsci/psychology/faculty.html?fpid=dale-stack). 

Current projects (that are not my dissertation) include:

1) Predicting intergenerational health outcomes from childhood risk factors

2) Predicting educational outcomes following a major educational reform PI: [Dr. Marie-Hélène Véronneau](https://professeurs.uqam.ca/professeur?c=veronneau.marie-helene) 

3) Understanding the bidirectional relations between parenting stress, parent-child support and child externalizing behavior using multiple informers

I have also been involved in the supervision of undergraduate student theses over the last 3 years. The topics included:

- The association between physical health in childhood and delinquency in adolescence

- Protective Factors against the Intergenerational Continuity of Risk for the
Development of Externalizing Behaviors in an At-Risk Sample

- Predicting recidivism using the NEO-5 personality inventory and crime onset

